### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #20.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
🤬 damn conda conflict descriptors.... I could never understand them...

**Comment by mariusvniekerk** [comment]
Fails due to the very strict https://github.com/conda-forge/aiomysql-feedstock/blob/master/recipe/meta.yaml#L25 requirement for which conda-forge actually has none of the packages!

**Comment by carlodri** [comment]
thanks @mariusvniekerk! Waiting for https://github.com/conda-forge/pymysql-feedstock/pull/9...

**Comment by carlodri** [comment]
superseded by #25

**Pull request closed without merging**
